world: rc_2027_red

robots:
  rc_2027:
    - name: "AT_R2"
      color: "red"
      x_pose: "-4.75"
      y_pose: "-5.00"
      z_pose: "0.15"
      yaw: "1.5708"

  rc_2027_red:
    - name: "AT_R2"
      color: "red"
      x_pose: "-4.75"
      y_pose: "-5.00"
      z_pose: "0.15"
      yaw: "1.5708"

  rc_2027_blue:
    - name: "AT_R2"
      color: "blue"
      x_pose: "4.75"
      y_pose: "-5.00"
      z_pose: "0.15"
      yaw: "1.5708"

  rc_2026:
    - name: "AT_R2"
      color: "red"
      x_pose: "0.4"
      y_pose: "4.55"
      z_pose: "0.6"
      yaw: "0"
